- .github/workflow/build-generic.yml
- .github/workflow/patch-generic.yml
- .github/workflow/release-generic.yml
Add new GitHub workflows for servers releases and CIs
> feat: add generic workflows for servers

- .github/workflows/patch-generic.yml
- .github/workflows/release-generic.yml
No
Fix the generic release workflow
Deploy the docker image before setting the git tag
Set the git tag before deploying the docker image
> Fix generic release steps order

- .github/workflows/build-generic.yml
> Add organizations for broadcasting event

- .github/workflows/patch-backend-lib-generic.yml
- .github/workflows/patch-frontend-app-generic.yml
- .github/workflows/release-frontend-app-generic.yml
> Push branch after patch backend lib

- .github/workflows/patch-frontend-app-generic.yml
> Fix patch frontend applications

- .github/workflows/build-backend-app-generic.yml
- .github/workflows/patch-backend-app-generic.yml
- .github/workflows/patch-backend-lib-generic.yml
- .github/workflows/release-backend-app-generic.yml
- .github/workflows/release-backend-lib-generic.yml
> java 17 -> java 21

- .github/workflows/build-backend-lib-generic.yml
NO
Feature
No generic backend lib build
generic backend lib build
> Add build-backend-lib-generic

- .github/workflows/patch-frontend-app-generic.yml
- .github/workflows/release-frontend-app-generic.yml
- .github/workflows/release-frontend-lib-generic.yml
Upgrade to Node 22
No.
Upgrade to latest LTS Node 22.
Use Node LTS 18.
Use Node LTS 22.
Upgrade to Node 22 locally or use `nvm use lts/jod`.
> Upgrade to Node 22

- .github/workflows/build-base-docker-image-generic.yml
- .github/workflows/patch-base-docker-image-generic.yml
- .github/workflows/release-base-docker-image-generic.yml
NO
Feature
No generic workflows for docker base images
generic workflow for docker base images
#15 first attempt had a typo we pushed -f to avoid a bad commit on main
> Workflows docker base image

- .github/workflows/release-frontend-lib-generic.yml
> Remove write permissions for frontend libraries workflow

- .github/workflows/release-frontend-lib-generic.yml
No.
Add [`provenance`](https://docs.npmjs.com/cli/v10/commands/npm-publish#provenance) on `npm publish`.
NPM libraries builds are published without provenance on npmjs.org registry.
As explain in https://github.blog/security/supply-chain-security/introducing-npm-package-provenance/  
It add a signature that a build published on the npmjs registry come from the Github-CI and also trace the workflow used.
**Does this PR introduce a …
> Add provenance on registry builds

- .github/workflows/release-backend-app-generic.yml
- .github/workflows/release-base-docker-image-generic.yml
- .github/workflows/release-frontend-app-generic.yml
NO
feature
anything unreviewed can be released
only main can be released
WIP TODO all workflows
> release from main only

- .github/workflows/build-backend-app-generic.yml
- .github/workflows/patch-backend-app-generic.yml
- .github/workflows/patch-backend-lib-generic.yml
- .github/workflows/patch-base-docker-image-generic.yml
- .github/workflows/patch-frontend-app-generic.yml
- .github/workflows/release-backend-app-generic.yml
- .github/workflows/release-backend-lib-generic.yml
- .github/workflows/release-base-docker-image-generic.yml
- .github/workflows/release-frontend-app-generic.yml
- .github/workflows/release-frontend-lib-generic.yml
bugfix
vulnerable to switch injection
safe against script injection
https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions#understanding-the-risk-of-script-injections
> Protectscriptinjection

- .github/workflows/release-frontend-lib-generic.yml
NO
bugfix
releases fail
releases work
fixup 28ac6b3a050 (#13)
npm error code EUSAGE
npm error Provenance generation in GitHub Actions requires "write" access to the "id-token" permission
> release-frontend-lib, add permission id-token:write

- .github/workflows/build-backend-lib-generic.yml
#31 
bugfix
build backend lib forgotten in script injection protection
build backend lib protected
> Fixup 70c6a19ac (#31) forgot this file

- .github/workflows/build-frontend-lib-generic.yml
NO
Feature
duplicated frontend lib build
generic frontend lib build (vite)
> Buildfrontendlib

- .github/workflows/release-backend-app-generic.yml
- .github/workflows/release-base-docker-image-generic.yml
- .github/workflows/release-frontend-app-generic.yml
- .github/workflows/release-sources-generic.yml
no
chore
check for omitted commits, then check merged in main 
check merged in main, then check for omitted commits
Checking in main first is more logical, it's a simpler check conceptually
> releases: check if commit is in main first

- .github/workflows/release-backend-lib-generic.yml
> fix release workflow

- .github/workflows/build-backend-app-generic.yml
- .github/workflows/build-backend-lib-generic.yml
- .github/workflows/patch-backend-app-generic.yml
- .github/workflows/release-backend-app-generic.yml
no
chore
dynamic sonar properties in workflow
static sonar properties in pom properties
move sonar informations from worfklow yaml to pom properties in every project
> remove inline sonar project properties

- .github/workflows/patch-frontend-app-generic.yml
no
bug fix
frontend app patch release crash
frontend app patch release works
> npm version "$RUNGHA_RELEASE_VERSION"
> npm error Invalid version: v2.16
should have been 2.16.0, not v2.16
regression from 70c6a19ac (#31)
> Fix patch-frontend-app-generic.yml

- .github/workflows/patch-backend-app-generic.yml
- .github/workflows/patch-backend-lib-generic.yml
- .github/workflows/patch-frontend-app-generic.yml
- .github/workflows/release-backend-app-generic.yml
- .github/workflows/release-backend-lib-generic.yml
- .github/workflows/release-frontend-app-generic.yml
- .github/workflows/release-frontend-lib-generic.yml
NO
feature
github app commits are not signed
github app commits are signed
> Use signed commits for releases

- .github/workflows/release-frontend-lib-generic.yml
no
feature
when providing a publish token, the release fails during npm publish because of missing 2FA but commits and tags have already been pushed to github
check before pushing/committing to github that the token has the correct type
it should reduce the number of cases where we have to cleanup
> Npmtokenautomation
